version: '3'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: almossar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '!+@_#)'
    ports:
      - 5432:5432
    volumes:
      - /data:/var/lib/postgresql/data

